"""The fsck TUI: changes listed, diffs in colour, written only on y."""

from __future__ import annotations

import asyncio
from pathlib import Path

from sorto.fsck import check, diff_text, prepare
from sorto.fsck_tui import FsckApp
from test_fsck import (  # noqa: F401  (fixture)
    HEALTH,
    HEALTH_NOTE,
    MONEY,
    MONEY_NOTE,
    Reviewer,
    tree,
)
from test_fsck_model import CATEGORIES, STRUCTURE


def _drive(root: Path, keys: list[str]):
    report = check(root)
    app = FsckApp(root, root.parent / "backups", report=report)

    async def go():
        async with app.run_test(size=(140, 40)) as pilot:
            await pilot.pause()
            shown = str(app.query_one("#body").render())
            for key in keys:
                await pilot.press(key)
                await pilot.pause()
            after = str(app.query_one("#body").render()) if app.is_running else ""
            return shown, after

    shown, after = asyncio.run(go())
    app.body_after = after
    return app, report, shown


def test_y_writes_the_change_shown_and_moves_on_n_skips(tree: Path) -> None:  # noqa: F811
    app, report, shown = _drive(tree, ["down", "y", "n", "q"])  # the list starts on the problems row
    first, second = report.changes[0], report.changes[1]
    assert first.rel.endswith("11.00 JDex/JDex.md") and second.rel.endswith("13.00 JDex/JDex.md")
    assert "Reported only" in shown  # what needs a human is read first
    assert "Records" in (tree / HEALTH / "11.00 JDex" / "JDex.md").read_text(encoding="utf-8")
    assert (tree / MONEY / "13.00 JDex" / "JDex.md").read_text(encoding="utf-8") == MONEY_NOTE
    assert app.status[:2] == ["written", "skipped"]
    assert app.return_value.written == 1 and app.return_value.declined == len(report.changes) - 1
    assert (tree.parent / "backups" / HEALTH / "11.00 JDex" / "JDex.md").read_text(encoding="utf-8") == HEALTH_NOTE


def test_quit_writes_nothing(tree: Path) -> None:  # noqa: F811
    before = {p: p.read_bytes() for p in tree.rglob("*.md")}
    app, report, _ = _drive(tree, ["q"])
    assert {p: p.read_bytes() for p in tree.rglob("*.md")} == before
    assert app.return_value.written == 0 and app.return_value.declined == len(report.changes)


def test_the_problems_row_lists_what_needs_a_human(tree: Path) -> None:  # noqa: F811
    app, report, _ = _drive(tree, ["home"])
    body = app.body_after
    assert "Reported only" in body and "generated by something else" in body
    app2, _, _ = _drive(tree, ["home", "y", "q"])  # y on the problems row does nothing
    assert app2.return_value.written == 0


def test_diffs_are_coloured(tree: Path) -> None:  # noqa: F811
    change = next(c for c in check(tree).changes if c.rel.endswith("13.00 JDex/JDex.md"))
    text = diff_text(change)
    styles = {str(span.style) for span in text.spans}
    assert "#7ee787" in styles and "#ff7b72" in styles and "#79c0ff" in styles
    added = next(s for s in text.spans if text.plain[s.start:s.end].startswith("+| 13.13"))
    assert str(added.style) == "#7ee787"


def test_the_review_runs_with_a_progress_bar_then_proposals_and_findings_come_first(tree: Path) -> None:  # noqa: F811
    app = FsckApp(tree, tree.parent / "backups", model="fake-35b",
                  prepare=lambda progress: prepare(tree, Reviewer(CATEGORIES, STRUCTURE), progress))

    async def go():
        async with app.run_test(size=(140, 40)) as pilot:
            head = str(app.query_one("#work-head").render())
            for _ in range(50):
                await pilot.pause(0.05)
                if app.report is not None:
                    break
            rows = [str(r.query_one("Label").render()) for r in app.query_one("#changes").children]
            first = str(app.query_one("#body").render())
            await pilot.press("q")
            return head, rows, first

    head, rows, first = asyncio.run(go())
    assert head == "The model fake-35b is reviewing the tree before anything is proposed"
    assert rows[:3] == ["◆ Structure proposals (1)", f"◆ Model findings ({len(app.report.insights.findings)})",
                        f"! Problems to look at ({len(app.report.problems)})"]
    assert "1. Merge Money into fewer IDs" in first and "What: Fold 13.11 Bank into 13.13 Invoices." in first
