"""sorto fsck: the JDex notes are brought in line with the folders, file by file, only when accepted."""

from __future__ import annotations

import io
import os
from pathlib import Path

import pytest

from conftest import make_engine
from sorto.cli import main
from sorto.fsck import EXIT_CLEAN, EXIT_FIXED, EXIT_LEFT, check, run
from sorto.jd import iter_jdex_entries, scan_jd

LIFE = "10-19 Life"
MONEY = f"{LIFE}/13 Money"
HEALTH = f"{LIFE}/11 Health"

MONEY_NOTE = """\
# 13.00 JDex — 13 Money

Bills go straight into the IDs. Moved here from 16.11 in the spring.

| ID | Name | Holds |
|----|------|-------|
| 13.11 | Bank | Statements |
| 13.12 | Taxes | Returns and decisions |
| 13.14 | Old savings | Closed accounts |

| ID | Source |
|----|--------|
| 13.11 | `old-bank/`, `statements/` |

- 13.15 Pension → now in 11.13
"""

HEALTH_NOTE = """\
# 11.00 JDex — 11 Health

- `11.11` Doctor visits — appointments and referrals
- `11.12` Patients — patient records
- `11.19` Dental — moved to the dentist's own ID
"""


class Reviewer:
    """Stands in for the structure model: canned answers per category, and for the whole tree."""

    model = "fake-35b"

    def __init__(self, categories=None, structure=None, fail=()):
        self.categories = categories or {}
        self.structure = structure or {"proposals": []}
        self.fail = set(fail)
        self.asked: list[str] = []

    def health(self):
        return True, "ok"

    def review_category(self, question: str) -> dict:
        self.asked.append(question)
        num = question.split("CATEGORY: ", 1)[1][:2]
        if num in self.fail:
            raise RuntimeError("model went away")
        return self.categories.get(num, {})

    def review_structure(self, question: str) -> dict:
        self.asked.append(question)
        return self.structure


@pytest.fixture
def tree(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("SORTO_HOME", str(tmp_path / "sorto-home"))
    root = tmp_path / "archive"
    for d in (
        "00-09 System/00 Admin/00.00 JDex",
        "00-09 System/00 Admin/00.01 Inbox",
        f"{MONEY}/13.00 JDex",
        f"{MONEY}/13.01 Inbox",
        f"{MONEY}/13.11 Bank",
        f"{MONEY}/13.12 Taxes",
        f"{MONEY}/13.13 Invoices",
        f"{HEALTH}/11.00 JDex",
        f"{HEALTH}/11.01 Inbox",
        f"{HEALTH}/11.11 Doctor visits",
        f"{HEALTH}/11.12 Records",
        f"{HEALTH}/11.13 Dental",
        f"{LIFE}/14 Travel/14.11 Trips",
    ):
        (root / d).mkdir(parents=True)
    (root / MONEY / "13.00 JDex" / "JDex.md").write_text(MONEY_NOTE, encoding="utf-8")
    (root / HEALTH / "11.00 JDex" / "JDex.md").write_text(HEALTH_NOTE, encoding="utf-8")
    (root / "00-09 System/00 Admin/00.00 JDex/00.00 JDex.md").write_text(
        "# JDex\nGenerated by make-tree.py: edit that, not this.\n\n- 13.11 Bank\n- 13.14 Old savings\n",
        encoding="utf-8",
    )
    return root


def _change(report, rel_end: str):
    return next(c for c in report.changes if c.rel.endswith(rel_end))


def test_table_entries_are_brought_in_line_and_everything_else_is_kept(tree: Path) -> None:
    report = check(tree)
    money = _change(report, "13.00 JDex/JDex.md")
    assert money.reasons == ["removed 13.14 Old savings: no such ID on disk", "added 13.13 Invoices"]
    lines = money.new.splitlines()
    assert "| 13.13 | Invoices | |" in lines  # in the table that has names, in number order, in its style
    assert lines.index("| 13.13 | Invoices | |") == lines.index("| 13.12 | Taxes | Returns and decisions |") + 1
    assert "13.14" not in money.new
    # Prose, the table of sources and the cross-reference stay exactly as they were.
    for kept in ("Bills go straight into the IDs. Moved here from 16.11 in the spring.",
                 "| 13.11 | `old-bank/`, `statements/` |", "- 13.15 Pension → now in 11.13"):
        assert kept in lines
    assert any("13.00 JDex/JDex.md: mentions IDs that are not on disk: 13.15, 16.11" in p for p in report.problems)


def test_list_entries_get_the_folder_name_and_a_renumbered_id(tree: Path) -> None:
    health = _change(check(tree), "11.00 JDex/JDex.md")
    assert health.reasons == ["11.12: name 'Patients' → 'Records' as on disk", "11.19 Dental is now 11.13"]
    assert health.new.splitlines()[2:] == [
        "- `11.11` Doctor visits — appointments and referrals",
        "- `11.12` Records — patient records",
        "- `11.13` Dental — moved to the dentist's own ID",
    ]


def test_a_generated_note_is_reported_not_changed(tree: Path) -> None:
    report = check(tree)
    assert not any(c.rel.endswith("00.00 JDex.md") for c in report.changes)
    (gen,) = [p for p in report.problems if "00.00 JDex.md" in p]
    assert "generated by something else, not changed" in gen
    assert gen.endswith("fix it in its generator: 1 listed ID(s) not on disk (13.14)")


def test_a_category_without_a_note_gets_one_with_its_folders(tree: Path) -> None:
    travel = _change(check(tree), "14.00 JDex/JDex.md")
    assert travel.old is None and travel.mkdirs == [f"{LIFE}/14 Travel/14.00 JDex", f"{LIFE}/14 Travel/14.01 Inbox"]
    assert travel.new == "# 14.00 JDex — 14 Travel\n\n- 14.11 Trips\n"


def test_structure_problems_are_only_reported(tree: Path) -> None:
    (tree / MONEY / "11.15 Misplaced").mkdir()
    (tree / HEALTH / "11.11 Doctor visits again").mkdir()
    (tree / HEALTH / "11.16 2231_0041").mkdir()
    (tree / "00-09 System" / "14 Wrong area").mkdir()
    problems = check(tree).problems
    assert f"{MONEY}/11.15 Misplaced: ID 11.15 is inside category 13" in problems
    assert any(p.startswith("ID 11.11 is used by 2 folders:") for p in problems)
    assert f"{HEALTH}/11.16 2231_0041: the name does not say what the ID holds" in problems
    assert "00-09 System/14 Wrong area: category 14 is outside its area 00-09" in problems


def test_without_a_terminal_and_without_yes_nothing_is_written(tree: Path) -> None:
    before = {p: p.read_bytes() for p in tree.rglob("*.md")}
    out = io.StringIO()
    status = run(tree, llm=Reviewer(), out=out, interactive=False)
    assert status == EXIT_LEFT
    assert {p: p.read_bytes() for p in tree.rglob("*.md")} == before
    assert not (tree / LIFE / "14 Travel" / "14.00 JDex").exists()
    assert "none written: run in a terminal to accept them one by one, or with --yes" in out.getvalue()


def test_each_file_is_written_only_when_accepted(tree: Path) -> None:
    answers = iter(["y", "n", "q"])
    out = io.StringIO()
    status = run(tree, llm=Reviewer(), out=out, ask=lambda _prompt: next(answers), interactive=True)
    assert status == EXIT_FIXED | EXIT_LEFT
    health = (tree / HEALTH / "11.00 JDex" / "JDex.md").read_text(encoding="utf-8")
    money = (tree / MONEY / "13.00 JDex" / "JDex.md").read_text(encoding="utf-8")
    assert "Records" in health and "11.13` Dental" in health  # first: accepted
    assert money == MONEY_NOTE  # second: declined
    assert not (tree / LIFE / "14 Travel" / "14.00 JDex").exists()  # quit before the third
    (backup,) = (tree.parent / "sorto-home" / "fsck-backups").glob(f"*/{HEALTH}/11.00 JDex/JDex.md")
    assert backup.read_text(encoding="utf-8") == HEALTH_NOTE


def test_yes_writes_everything_and_a_second_run_finds_only_what_needs_a_human(tree: Path) -> None:
    assert run(tree, llm=Reviewer(), yes=True, out=io.StringIO()) == EXIT_FIXED | EXIT_LEFT  # the generated note is left
    assert (tree / LIFE / "14 Travel" / "14.01 Inbox").is_dir()
    report = check(tree)
    assert report.changes == []
    assert all("00.00 JDex.md" in p or "mentions IDs" in p for p in report.problems)
    (tree / "00-09 System/00 Admin/00.00 JDex/00.00 JDex.md").write_text("# 00.00 JDex — 00 Admin\n", encoding="utf-8")
    for note in tree.rglob("JDex.md"):  # drop the prose mentions too: then all agrees
        note.write_text("".join(ln for ln in note.read_text(encoding="utf-8").splitlines(keepends=True)
                                if "16.11" not in ln and "→" not in ln), encoding="utf-8")
    out = io.StringIO()
    assert run(tree, llm=Reviewer(), out=out, interactive=False) == EXIT_CLEAN
    assert "the structure and the JDex notes agree" in out.getvalue()


def test_a_note_changed_meanwhile_is_not_overwritten(tree: Path) -> None:
    note = tree / HEALTH / "11.00 JDex" / "JDex.md"

    def ask(_prompt: str) -> str:
        note.write_text(HEALTH_NOTE + "- 11.13 Dental\n", encoding="utf-8")  # the user edits it meanwhile
        return "y"

    out = io.StringIO()
    run(tree, llm=Reviewer(), out=out, ask=ask, interactive=True)
    assert note.read_text(encoding="utf-8").endswith("- 11.13 Dental\n")
    assert "changed on disk since it was checked" in out.getvalue()


def test_cli_fsck(tree: Path, capsys, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr("sorto.fsck_model.structure_llm", lambda _root, _model=None: Reviewer())
    assert main(["fsck", str(tree), "--yes"]) == EXIT_FIXED | EXIT_LEFT
    assert "change(s) written; previous versions in" in capsys.readouterr().out


def test_table_names_come_from_the_name_column(tree: Path) -> None:
    entries = [e for _n, e in iter_jdex_entries(MONEY_NOTE)]
    assert [(e.jd_id, e.name) for e in entries] == [
        ("13.11", "Bank"), ("13.12", "Taxes"), ("13.14", "Old savings"), ("13.11", ""),
    ]
    assert entries[0].description == "Statements"


def test_a_categorys_own_note_describes_its_ids_before_a_tree_wide_index(tree: Path) -> None:
    (tree / "00-09 System/00 Admin/00.00 JDex/00.00 JDex.md").write_text(
        "- 13.11 Bank — Source: old drive 06.11\n", encoding="utf-8"
    )
    assert scan_jd(tree).get("13.11").description == "Statements"


def test_a_run_says_when_the_notes_and_folders_disagree(inbox: Path, target: Path, cfg) -> None:
    (inbox / "invoice.txt").write_text("Invoice", encoding="utf-8")
    engine = make_engine(cfg)
    engine.run_until_idle(timeout=30)
    text = engine.run_log.path.read_text(encoding="utf-8")
    assert "JDex: JDex notes and folders disagree: " in text and f"sorto fsck {target} shows them" in text


OLD_MONEY_NOTE = """\
# 13.00 JDex — the old drive's money index

- 13.11 Bank
- 13.15 Pension
- 13.16 Savings account
- 13.17 Shares
- 13.12 Tax returns
"""


def test_a_second_out_of_date_note_is_a_leftover_and_gets_no_changes(tree: Path) -> None:
    old = tree / MONEY / "13.00 JDex" / "Old index.md"
    old.write_text(OLD_MONEY_NOTE, encoding="utf-8")
    os.utime(old, (1_600_000_000, 1_600_000_000))  # older than the current note
    report = check(tree)
    (problem,) = [p for p in report.problems if "notes in one JDex folder" in p]
    assert problem.startswith(f"{MONEY}/13.00 JDex: 2 notes in one JDex folder: ")
    assert "JDex.md (\"13.00 JDex — 13 Money\"" in problem
    assert "Old index.md (\"13.00 JDex — the old drive's money index\", 2020-09-13" in problem
    assert "5 entries, 3 for IDs no longer on disk, 1 with another name" in problem
    assert "2 IDs are listed in both" in problem
    assert "Old index.md looks like a leftover from an earlier index" in problem
    assert not any(c.rel.endswith("Old index.md") for c in report.changes)
    assert any(c.rel.endswith("13.00 JDex/JDex.md") for c in report.changes)  # the current note still is


def test_two_up_to_date_notes_are_reported_but_neither_is_called_a_leftover(tree: Path) -> None:
    (tree / MONEY / "13.00 JDex" / "Notes.md").write_text("# Notes\n\n- 13.13 Invoices — paid bills\n", encoding="utf-8")
    report = check(tree)
    (problem,) = [p for p in report.problems if "notes in one JDex folder" in p]
    assert "leftover" not in problem and problem.endswith("Keep one note per JDex folder, or say in each what it is for")
    assert any(c.rel.endswith("13.00 JDex/JDex.md") for c in report.changes)


def test_files_and_folders_that_are_not_notes_are_reported(tree: Path) -> None:
    folder = tree / MONEY / "13.00 JDex"
    (folder / "statement-march.pdf").write_bytes(b"%PDF")
    (folder / "scans").mkdir()
    (folder / ".DS_Store").write_bytes(b"\0")  # hidden: not reported
    before = sorted(p.name for p in folder.iterdir())
    problems = check(tree).problems
    assert (f"{MONEY}/13.00 JDex: 2 thing(s) that are not notes: scans/, statement-march.pdf; a JDex folder holds "
            "the category's notes, files belong in an ID (move them yourself)") in problems
    assert sorted(p.name for p in folder.iterdir()) == before  # nothing moved
