"""``sorto fsck``: check a Johnny.Decimal tree's structure and its JDex notes, and offer fixes.

The tree on disk is the truth; the notes are brought in line with it. Every
change to a file is shown first and written only when the user accepts it,
file by file (``--yes`` accepts all). Before a note is changed its previous
version is copied to sorto's own directory. Folders are never renamed or
moved: what is wrong in the structure itself is reported, not fixed.

What is proposed, per note:

- an entry for every ID of the note's own category that the notes of that
  category do not list (a note in ``31.00 JDex/`` is responsible for 31);
- an entry whose ID is not on disk is removed, or, when a folder with the
  same name exists under another number, changed to that number;
- an entry whose name differs from the folder's name gets the folder's name.

A category without a note gets one (and its ``NN.00`` / ``NN.01`` folders).
Prose that merely mentions an ID that is gone is history, not an entry: it is
reported and left alone. A note that says it is generated by something else
is not changed; what it lacks is reported, to be fixed in its generator.
"""

from __future__ import annotations

import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, TextIO

from rich.console import Console
from rich.text import Text

from sorto.jd import (
    AREA_RE,
    CATEGORY_RE,
    ID_RE,
    MAX_JDEX_BYTES,
    JDIndex,
    _dirs,
    _folder_key,
    _md_files,
    clean_id_name,
    iter_jdex_entries,
    note_category,
    parse_jdex_entry,
    scan_jd,
)
from sorto.util import state_home, whole_tree

GENERATED_RE = re.compile(r"\b(generated|generoitu|do not edit|älä muokkaa)\b", re.IGNORECASE)
ID_MENTION_RE = re.compile(r"(?<![\d.])(\d{2}\.\d{2})(?!\d|\.\d)")
DEFAULT_NOTE_NAME = "JDex.md"

# fsck(8)-style exit status: bits that can be combined.
EXIT_CLEAN = 0
EXIT_FIXED = 1
EXIT_LEFT = 4


@dataclass
class Change:
    """One thing to accept or decline: a note's new content, and folders to create with it."""

    rel: str  # the note, relative to the target ("" when only folders are created)
    old: str | None  # None: a new note
    new: str
    reasons: list[str] = field(default_factory=list)
    mkdirs: list[str] = field(default_factory=list)

    def diff(self) -> str:
        lines = [f"+ folder {d}/" for d in self.mkdirs]
        if self.rel:
            old = (self.old or "").splitlines(keepends=True)
            new = self.new.splitlines(keepends=True)
            label = "/dev/null" if self.old is None else f"a/{self.rel}"
            lines += [
                ln.rstrip("\n")
                for ln in difflib.unified_diff(old, new, fromfile=label, tofile=f"b/{self.rel}", n=1)
            ]
        return "\n".join(lines)


@dataclass
class Report:
    changes: list[Change] = field(default_factory=list)
    problems: list[str] = field(default_factory=list)  # reported only: nothing to accept
    mismatches: dict[str, str] = field(default_factory=dict)  # ID -> the name a note gives it, unlike the folder's
    insights: Any = None  # sorto.fsck_model.Insights once the model has reviewed the tree

    @property
    def clean(self) -> bool:
        found = self.insights is not None and (self.insights.findings or self.insights.proposals)
        return not self.changes and not self.problems and not found


# ------------------------------------------------------------------ checking


def check(target: Path, insights: Any = None) -> Report:
    """Everything that is wrong, as changes to accept and problems to report. Reads only.

    With the model's *insights*, new and description-less entries get the
    descriptions it wrote, and a note's name is not changed where the model
    found the folder's name to be the wrong one.
    """
    root = Path(target).expanduser().resolve()
    index = scan_jd(root)
    report = Report(insights=insights)
    descriptions = dict(getattr(insights, "descriptions", {}) or {})
    folder_wrong = dict(getattr(insights, "folder_name_wrong", {}) or {})
    report.problems += _structure_problems(root)
    notes = _notes(root, index)
    folder_problems, leftovers = _jdex_folder_problems(root, index, notes)
    report.problems += folder_problems
    notes = {p: t for p, t in notes.items() if p not in leftovers}  # not polished before the user decides
    listed: dict[str, set[str]] = {}  # category -> IDs its own notes list
    for path, text in notes.items():
        cat = note_category(path)
        if cat:
            entries = {e.jd_id for e in _entries(text)}
            listed.setdefault(cat, set()).update(entries)
    for path, text in notes.items():
        rel = path.relative_to(root).as_posix()
        if GENERATED_RE.search("\n".join(text.splitlines()[:15])):
            report.problems += _generated_problems(rel, text, index, note_category(path))
            continue
        if whole_tree(path, stop=root) is not None:
            report.problems.append(f"{rel}: inside a git repository or software package; not changed")
            continue
        new, reasons, mentions = _fixed_note(
            text, index, note_category(path), listed, notes, path,
            descriptions=descriptions, folder_wrong=folder_wrong, mismatches=report.mismatches,
        )
        if mentions:
            report.problems.append(f"{rel}: mentions IDs that are not on disk: {', '.join(mentions)} (left as is)")
        if new != text:
            report.changes.append(Change(rel=rel, old=text, new=new, reasons=reasons))
    report.changes += _missing_notes(root, index, notes, descriptions)
    for jd_id, why in sorted(folder_wrong.items()):
        if jd_id in report.mismatches and jd_id in index.items:
            report.problems.append(
                f"{index.items[jd_id].rel}: the model finds the note's name \"{report.mismatches[jd_id]}\" fits "
                f"the files better than the folder's ({why}); rename the folder yourself if you agree"
            )
    return report


def prepare(target: Path, llm: Any, progress: Any = None) -> Report:
    """The rule checks, the model's review of every category and of the whole tree, then the changes."""
    from sorto.fsck_model import analyse

    root = Path(target).expanduser().resolve()
    first = check(root)
    insights = analyse(root, scan_jd(root), first.mismatches, llm, progress)
    return check(root, insights)


def _notes(root: Path, index: JDIndex) -> dict[Path, str]:
    """The JDex notes: Markdown files in every ``NN.00`` folder, and ``*JDex*.md`` in the root."""
    paths: list[Path] = []
    for item in index.items.values():
        if item.is_index:
            paths += _md_files(root / item.rel)
    paths += [p for p in _md_files(root) if "jdex" in p.name.lower()]
    notes = {}
    for path in sorted(set(paths)):
        try:
            if path.stat().st_size <= MAX_JDEX_BYTES:
                notes[path] = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
    return notes


LEFTOVER_SHARE = 0.25  # this much of a note's entries out of date (and at least LEFTOVER_MIN) ...
LEFTOVER_MIN = 3  # ... and an older sibling note in the same folder: a leftover from an earlier index


def _jdex_folder_problems(root: Path, index: JDIndex, notes: dict[Path, str]) -> tuple[list[str], set[Path]]:
    """What should not be in a category's JDex folder: a second note, and anything that is not a note.

    A JDex folder holds the category's own note. Several notes in one folder
    usually mean an older index was left behind next to the current one; each
    is described (heading, date, entries, how many are out of date, overlap),
    and one that is clearly out of date and older than its sibling is called a
    leftover and gets no proposed changes until the user has decided which
    note the folder keeps. Files and folders that are not notes belong in an
    ID. Nothing is moved or deleted: these are reported only.
    """
    problems: list[str] = []
    leftovers: set[Path] = set()
    for item in sorted(index.items.values(), key=lambda i: i.id):
        if not item.is_index:
            continue
        folder = root / item.rel
        try:
            with os.scandir(folder) as it:
                found = sorted((e for e in it if not e.name.startswith(".")), key=lambda e: e.name.lower())
        except OSError:
            continue
        md = [Path(e.path) for e in found if e.is_file(follow_symlinks=False) and e.name.lower().endswith(".md")]
        others = [e.name + ("/" if e.is_dir(follow_symlinks=False) else "") for e in found if Path(e.path) not in md]
        if others:
            problems.append(
                f"{item.rel}: {len(others)} thing(s) that are not notes: {', '.join(others[:8])}"
                + (", …" if len(others) > 8 else "")
                + "; a JDex folder holds the category's notes, files belong in an ID (move them yourself)"
            )
        if len(md) < 2:
            continue
        facts, stale, ids = [], {}, {}
        for path in md:
            text = notes.get(path, "")
            entries = _entries(text)
            gone = sum(e.jd_id not in index.items for e in entries)
            renamed = sum(
                e.jd_id in index.items and bool(e.name) and len(e.name.split()) <= 6
                and not _same_name(e.name, index.items[e.jd_id].name)
                for e in entries
            )
            ids[path] = {e.jd_id for e in entries}
            heading = next((ln.lstrip("# ").strip() for ln in text.splitlines() if ln.startswith("#")), "")
            try:
                st = path.stat()
                when, size = datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d"), st.st_size
            except OSError:
                when, size = "?", 0
            generated = bool(GENERATED_RE.search("\n".join(text.splitlines()[:15])))
            out_of_date = gone + renamed
            if entries and out_of_date >= LEFTOVER_MIN and out_of_date / len(entries) >= LEFTOVER_SHARE:
                stale[path] = st.st_mtime if when != "?" else 0.0
            facts.append(
                f"{path.name} (\"{heading[:60]}\", {when}, {size / 1000:.1f} kB"
                + (", generated" if generated else "")
                + f", {len(entries)} entries, {gone} for IDs no longer on disk, {renamed} with another name)"
            )
        newest = max(md, key=lambda p: p.stat().st_mtime if p.exists() else 0.0)
        for path in stale:
            if path != newest and len(stale) < len(md):
                leftovers.add(path)
        a, b = md[0], md[1]
        both = len(ids[a] & ids[b]) if len(md) == 2 else None
        text = f"{item.rel}: {len(md)} notes in one JDex folder: {'; '.join(facts)}"
        if both is not None:
            text += f"; {both} IDs are listed in both"
        if leftovers & set(md):
            names = ", ".join(p.name for p in md if p in leftovers)
            text += (f". {names} looks like a leftover from an earlier index (older, much of it out of date): it gets "
                     "no proposed changes; keep one note and move the other out yourself")
        else:
            text += ". Keep one note per JDex folder, or say in each what it is for"
        problems.append(text)
    return problems, leftovers


def _entries(text: str):
    return [e for _n, e in iter_jdex_entries(text)]


def _structure_problems(root: Path) -> list[str]:
    """Misplaced and duplicate numbers. These need a human: folders are never renamed or moved."""
    problems = []
    seen_ids: dict[str, list[str]] = {}
    seen_cats: dict[str, list[str]] = {}
    for top in _dirs(root):
        area = AREA_RE.match(top.name)
        if not area:
            continue
        low, high = int(area.group(1)), int(area.group(2))
        for cat in _dirs(Path(top.path)):
            cm = CATEGORY_RE.match(cat.name)
            if not cm or ID_RE.match(cat.name):
                continue
            num = cm.group(1)
            rel = f"{top.name}/{cat.name}"
            seen_cats.setdefault(num, []).append(rel)
            if not low <= int(num) <= high:
                problems.append(f"{rel}: category {num} is outside its area {area.group(1)}-{area.group(2)}")
            for item in _dirs(Path(cat.path)):
                im = ID_RE.match(item.name)
                if not im:
                    continue
                jd_id = f"{im.group(1)}.{im.group(2)}"
                seen_ids.setdefault(jd_id, []).append(f"{rel}/{item.name}")
                if int(im.group(2)) > 10 and not clean_id_name(im.group(3)):
                    problems.append(f"{rel}/{item.name}: the name does not say what the ID holds")
                if im.group(1) != num:
                    problems.append(f"{rel}/{item.name}: ID {jd_id} is inside category {num}")
    for kind, seen in (("category", seen_cats), ("ID", seen_ids)):
        for num, rels in sorted(seen.items()):
            if len(rels) > 1:
                problems.append(f"{kind} {num} is used by {len(rels)} folders: {'; '.join(rels)}")
    return problems


def _generated_problems(rel: str, text: str, index: JDIndex, category: str) -> list[str]:
    entries = {e.jd_id for e in _entries(text)}
    real = {i for i, it in index.items.items() if not it.is_index and not it.is_inbox}
    if len({e[:2] for e in entries}) > 1:
        expected = real  # a tree-wide index lists everything
    else:
        expected = {i for i in real if i[:2] == category} if category else set()
    missing = sorted(expected - entries)
    stale = sorted(e for e in entries if e not in index.items)
    out = []
    if missing or stale:
        parts = []
        if missing:
            parts.append(f"{len(missing)} ID(s) on disk not listed ({_few(missing)})")
        if stale:
            parts.append(f"{len(stale)} listed ID(s) not on disk ({_few(stale)})")
        out.append(f"{rel}: generated by something else, not changed; fix it in its generator: {'; '.join(parts)}")
    return out


def _few(ids: list[str], n: int = 8) -> str:
    return ", ".join(ids[:n]) + (f", +{len(ids) - n} more" if len(ids) > n else "")


def _fixed_note(
    text: str, index: JDIndex, category: str, listed: dict[str, set[str]], notes: dict[Path, str], path: Path,
    *, descriptions: dict[str, str] | None = None, folder_wrong: dict[str, str] | None = None,
    mismatches: dict[str, str] | None = None,
) -> tuple[str, list[str], list[str]]:
    """The note with its entries brought in line with the disk: (new text, reasons, gone IDs in prose).

    Only entry lines change. Every other line (headings, prose, history) is
    kept exactly as it is; IDs it mentions that are gone are reported.
    """
    lines = text.splitlines(keepends=True)
    entries = dict(iter_jdex_entries(text))
    in_note = {e.jd_id for e in entries.values()}
    by_name: dict[str, list[str]] = {}
    for jd_id, item in index.items.items():
        by_name.setdefault(_folder_key(item.name), []).append(jd_id)
    out: list[str] = []
    reasons: list[str] = []
    mentions: set[str] = set()
    for n, line in enumerate(lines):
        entry = entries.get(n)
        if entry is None:
            mentions.update(i for i in ID_MENTION_RE.findall(line) if i not in index.items)
            out.append(line)
            continue
        item = index.items.get(entry.jd_id)
        label = f"{entry.jd_id} {entry.name}".strip()
        if item is None:
            # Renumbered within its category: the same name under another number.
            moved = [i for i in by_name.get(_folder_key(entry.name), []) if i[:2] == entry.jd_id[:2]] \
                if entry.name else []
            if len(moved) == 1 and moved[0] not in in_note:
                out.append(_replace_id(line, entry.jd_id, moved[0]))
                reasons.append(f"{label} is now {moved[0]}")
            else:
                reasons.append(f"removed {label}: no such ID on disk")
            continue
        descriptions = descriptions or {}
        folder_wrong = folder_wrong or {}
        # A long "name" is a sentence about the ID, not its name: left alone.
        if entry.name and len(entry.name.split()) <= 6 and not _same_name(entry.name, item.name) and entry.name in line:
            if mismatches is not None:
                mismatches[entry.jd_id] = entry.name
            if entry.jd_id not in folder_wrong:  # the model found the note right and the folder wrong: kept
                line = line.replace(entry.name, item.name, 1)
                reasons.append(f"{entry.jd_id}: name {entry.name!r} → {item.name!r} as on disk")
        desc = descriptions.get(entry.jd_id) if entry.jd_id[:2] == category else None
        if desc and (not entry.description or PROVENANCE_ONLY_RE.match(entry.description)) and entry.name \
                and desc not in line:
            line = _with_description(line, entry, desc)
            reasons.append(f"{entry.jd_id}: description from the model: {desc}")
        out.append(line)
    # Entries for the category's IDs that none of its notes list, into the first note of its folder.
    if category and path == _first_note_of(category, notes):
        have = listed.get(category, set()) | {e.jd_id for e in _entries("".join(out))}
        for item in index.category_ids(category):
            if item.id not in have:
                desc = (descriptions or {}).get(item.id) or item.description
                out = _insert_entry(out, item.id, item.name, desc)
                reasons.append(f"added {item.id} {item.name}" + (f" — {desc}" if desc else ""))
    return "".join(out), reasons, sorted(mentions)


def _same_name(written: str, on_disk: str) -> bool:
    """ "Models (3D prints)" and "Models" are the same name; a note may add a few words."""
    a, b = _folder_key(written), _folder_key(on_disk)
    return bool(a and b) and (a.startswith(b) or b.startswith(a))


def _first_note_of(category: str, notes: dict[Path, str]) -> Path | None:
    own = [p for p, t in notes.items() if note_category(p) == category
           and not GENERATED_RE.search("\n".join(t.splitlines()[:15]))]
    with_entries = [p for p in own if _entries(notes[p])]
    return (with_entries or own or [None])[0]


def _replace_id(line: str, old: str, new: str) -> str:
    return re.sub(rf"(?<![\d.]){re.escape(old)}(?![\d.])", new, line, count=1)


PROVENANCE_ONLY_RE = re.compile(r"^\s*(source|sources|from|lähde|lähteet)\s*:", re.IGNORECASE)


def _with_description(line: str, entry, desc: str) -> str:
    """The entry line with *desc* added: after the name in a list item, into an empty cell in a table row."""
    end = "\n" if line.endswith("\n") else ""
    body = line.rstrip("\n")
    if not entry.table:
        if entry.description and PROVENANCE_ONLY_RE.match(entry.description):
            return f"{body.rstrip()} ({desc}){end}"  # "— Source: old drive (Bills from shops)": both kept
        return f"{body.rstrip()} — {desc}{end}"
    indent = re.match(r"^\s*", body).group(0)
    cells = body.strip().strip("|").split("|")
    if len(cells) < 3 or any(c.strip() for c in cells[2:]):
        return line  # no description column, or it is not empty
    cells[2] = f" {desc} "
    return f"{indent}|{'|'.join(cells)}|{end}"


def _insert_entry(lines: list[str], jd_id: str, name: str, desc: str = "") -> list[str]:
    """Add an entry in ID order, in the style of the note's other entries (list item or table row)."""
    entries = list(iter_jdex_entries("".join(lines)))
    named = [(i, e) for i, e in entries if e.name]  # not into a table of sources that has no names
    same = [(i, e) for i, e in named if e.jd_id[:2] == jd_id[:2]]
    entries = same or named or entries
    if not entries:
        tail = "" if not lines or lines[-1].endswith("\n") else "\n"
        blank = "\n" if lines and lines[-1].strip() else ""
        return [*lines, tail + blank, f"- {jd_id} {name}" + (f" — {desc}" if desc else "") + "\n"]
    after = entries[-1]
    for i, e in entries:
        if e.jd_id > jd_id:
            break
        after = (i, e)
    pos, template = after
    if template.jd_id > jd_id:
        pos -= 1  # every entry has a higher number: goes before the first
    new = _like(lines[after[0]], template, jd_id, name)
    if desc:
        new = _with_description(new, parse_jdex_entry(new) or template, desc)
    return [*lines[: pos + 1], new, *lines[pos + 1:]]


def _like(line: str, entry, jd_id: str, name: str) -> str:
    indent = re.match(r"^\s*", line).group(0)
    if entry.table:
        cells = line.strip().strip("|").split("|")
        rest = " |" * max(0, len(cells) - 2)
        return f"{indent}| {jd_id} | {name} |{rest}\n"
    bullet = re.match(r"^\s*([-*+])", line).group(1)
    if re.match(r"^\s*[-*+]\s+`\d{2}\.\d{2}`", line):
        return f"{indent}{bullet} `{jd_id}` {name}\n"
    if re.match(r"^\s*[-*+]\s+`\d{2}\.\d{2}\s", line):
        return f"{indent}{bullet} `{jd_id} {name}`\n"
    return f"{indent}{bullet} {jd_id} {name}\n"


def _missing_notes(
    root: Path, index: JDIndex, notes: dict[Path, str], descriptions: dict[str, str] | None = None
) -> list[Change]:
    """Categories with no note: the note, and the ``NN.00`` and ``NN.01`` folders it needs."""
    names = Counter(p.name for p in notes if note_category(p))
    note_name = names.most_common(1)[0][0] if names else DEFAULT_NOTE_NAME
    changes = []
    for num, folder in sorted(index.categories.items()):
        has_note = any(note_category(p) == num for p in notes)
        jdex = index.items.get(f"{num}.00")
        inbox = index.items.get(f"{num}.01")
        if has_note and inbox is not None:
            continue
        cat_rel = index.category_rels[num]
        mkdirs = []
        if jdex is None:
            mkdirs.append(f"{cat_rel}/{num}.00 JDex")
        if inbox is None:
            mkdirs.append(f"{cat_rel}/{num}.01 Inbox")
        if has_note:
            changes.append(Change(rel="", old=None, new="", reasons=[f"{folder}: no {num}.01 Inbox"], mkdirs=mkdirs))
            continue
        jdex_rel = jdex.rel if jdex is not None else f"{cat_rel}/{num}.00 JDex"
        name = re.sub(r"^\d{2}\.00", f"{num}.00", note_name)
        body = [f"# {num}.00 JDex — {folder}\n", "\n"]
        for i in index.category_ids(num):
            desc = (descriptions or {}).get(i.id) or i.description
            body.append(f"- {i.id} {i.name}" + (f" — {desc}" if desc else "") + "\n")
        changes.append(Change(
            rel=f"{jdex_rel}/{name}", old=None, new="".join(body),
            reasons=[f"{folder} has no JDex note"], mkdirs=mkdirs,
        ))
    return changes


# ------------------------------------------------------------------ applying


def apply(root: Path, change: Change, backups: Path) -> None:
    """Write one accepted change: folders first, then the note. The old note is copied to *backups*.

    A note that changed on disk since it was read is not touched. A new note
    never replaces a file that appeared meanwhile.
    """
    root = Path(root).resolve()
    for rel in change.mkdirs:
        (root / rel).mkdir(exist_ok=True)
    if not change.rel:
        return
    path = root / change.rel
    if change.old is None:
        with open(path, "x", encoding="utf-8") as fp:
            fp.write(change.new)
        return
    if path.read_text(encoding="utf-8", errors="replace") != change.old:
        raise OSError(f"{change.rel} changed on disk since it was checked; run sorto fsck again")
    copy = backups / change.rel
    copy.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, copy)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".sorto-partial", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fp:
            fp.write(change.new)
            fp.flush()
            os.fsync(fp.fileno())
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


DIFF_STYLES = (
    ("+ folder ", "bold #7ee787"),
    ("+++", "bold #e6edf3"),
    ("---", "bold #e6edf3"),
    ("@@", "#79c0ff"),
    ("+", "#7ee787"),
    ("-", "#ff7b72"),
)


def diff_text(change: Change) -> Text:
    """The change's diff with colours: additions green, removals red, hunk headers blue."""
    text = Text()
    for line in change.diff().splitlines():
        style = next((s for prefix, s in DIFF_STYLES if line.startswith(prefix)), "#8b949e")
        text.append(line + "\n", style=style)
    return text


def run(
    target: Path,
    *,
    yes: bool = False,
    out: TextIO | None = None,
    ask: Callable[[str], str] | None = None,
    interactive: bool | None = None,
    tui: bool | None = None,
    llm: Any = None,
    model: str | None = None,
) -> int:
    """Review *target* with the model, show each change and write the accepted ones. fsck-style exit status.

    The structure model always reviews the tree first. In a terminal that and
    the changes are shown in a TUI (``tui=False``: plain text, asking each
    time). Without a terminal nothing is written unless *yes*. Colours only
    when the output is a terminal.
    """
    console = _console(out or sys.stdout)
    root = Path(target).expanduser().resolve()
    if not root.is_dir():
        print(f"error: target is not a directory: {root}", file=sys.stderr)
        return 8
    if llm is None:
        from sorto.fsck_model import structure_llm

        llm = structure_llm(root, model)
    model = str(getattr(llm, "model", ""))
    health = getattr(llm, "health", None)
    if health is not None:
        ok, detail = health()
        if not ok:
            print(f"error: sorto fsck needs the model {model} to review the tree first: {detail}", file=sys.stderr)
            return 8
    if interactive is None:
        interactive = sys.stdin.isatty()
    if tui is None:
        tui = interactive and sys.stdout.isatty() and out is None
    backups = state_home() / "fsck-backups" / datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    try:
        if tui and not yes:
            from sorto.fsck_tui import FsckApp

            app = FsckApp(root, backups, prepare=lambda progress: prepare(root, llm, progress), model=model)
            outcome = app.run()
            report = app.report
            if report is None:
                console.print(Text("the review did not finish; nothing was written", style="#d29922"))
                return EXIT_LEFT
            written, declined = (outcome.written, outcome.declined) if outcome else (0, len(report.changes))
            _summary(console, report, written, backups)
            return _status(written, declined, report)
        report = prepare(root, llm, _plain_progress(_console(sys.stderr)))
    finally:
        release = getattr(llm, "release", None)
        if release is not None:
            try:
                release()
            except Exception:
                pass
    if report.clean:
        console.print(Text(f"{root}: the structure and the JDex notes agree", style="#7ee787"))
        return EXIT_CLEAN
    _print_insights(console, report)
    for line in report.problems:
        console.print(Text.assemble(("! ", "bold #d29922"), line))
    ask = ask or input
    written = declined = 0
    for n, change in enumerate(report.changes, 1):
        console.print(Text.assemble(
            "\n", (f"[{n}/{len(report.changes)}] ", "#8b949e"), (change.rel or ", ".join(change.mkdirs), "bold"),
        ))
        for reason in change.reasons:
            console.print(Text.assemble(("  • ", "#ffa657"), reason))
        console.print(diff_text(change), end="")
        if not yes:
            if not interactive:
                declined += 1
                continue
            answer = _ask(ask, change, console)
            if answer == "q":
                declined += len(report.changes) - n + 1
                break
            if answer != "y":
                declined += 1
                continue
        try:
            apply(root, change, backups)
            written += 1
            console.print(Text("  written", style="#7ee787"))
        except OSError as e:
            declined += 1
            console.print(Text(f"  not written: {e}", style="#d29922"))
    if not yes and not interactive and report.changes:
        console.print(f"\n{len(report.changes)} change(s) proposed, none written: run in a terminal to accept "
                      "them one by one, or with --yes")
    _summary(console, report, written, backups)
    return _status(written, declined, report)


def _console(stream: TextIO) -> Console:
    """Colours only on a terminal, whatever the environment asks for: a log file or a pipe gets plain text."""
    tty = bool(getattr(stream, "isatty", lambda: False)())
    return Console(file=stream, highlight=False, soft_wrap=True, force_terminal=tty,
                   color_system="auto" if tty else None)


def _plain_progress(console: Console):
    """One line per category (and per phase) on stderr while the model works."""
    from sorto.fsck_model import eta_text

    last = {"phase": "", "done": -1}

    def show(p) -> None:
        if p.phase == last["phase"] and p.done == last["done"]:
            return
        if p.phase == "scanning" and last["phase"] == "scanning":
            return
        last["phase"], last["done"] = p.phase, p.done
        if p.phase == "scanning":
            console.print(Text(f"fsck: scanning {p.total} ID folders", style="#8b949e"))
        elif p.phase == "thinking":
            console.print(Text.assemble(("fsck: reviewing ", "#8b949e"), (f"{p.done + 1}/{p.total} ", "bold"),
                                        p.current, (f"  about {eta_text(p.eta_s)} left", "#d2a8ff")))
        elif p.phase == "structure":
            console.print(Text.assemble(("fsck: thinking about the whole structure", "#8b949e"),
                                        (f"  about {eta_text(p.eta_s)}", "#d2a8ff")))

    return show


def _print_insights(console: Console, report: Report) -> None:
    insights = report.insights
    if insights is None:
        return
    if insights.proposals:
        console.print(Text("\nStructure proposals (nothing here is applied; folders are never renamed or moved)",
                           style="bold #79c0ff"))
        for n, p in enumerate(insights.proposals, 1):
            console.print(Text(f"\n{n}. {p.title}", style="bold #79c0ff"))
            console.print(Text.assemble(("What: ", "bold"), p.change))
            console.print(Text.assemble(("Why: ", "bold"), p.why))
            for s, step in enumerate(p.steps, 1):
                console.print(f"  {s}. {step}")
            console.print(Text.assemble(("Effort: ", "bold"), (p.effort, "#d2a8ff")))
            for w in p.warnings:
                console.print(Text.assemble(("Check: ", "bold #d29922"), (w, "#d29922")))
    if insights.findings or insights.errors:
        console.print(Text("\nModel findings", style="bold #d2a8ff"))
        for f in insights.findings:
            console.print(Text.assemble((f"{f.kind:<10}", "bold #d2a8ff"), f.text))
        for e in insights.errors:
            console.print(Text.assemble(("error     ", "bold #f85149"), e))
    console.print()


def _summary(console: Console, report: Report, written: int, backups: Path) -> None:
    if written:
        console.print(Text(f"\n{written} change(s) written; previous versions in {backups}", style="#7ee787"))
    if report.problems:
        console.print(Text(f"{len(report.problems)} problem(s) need a human; sorto fsck lists them", style="#d29922"))


def _status(written: int, declined: int, report: Report) -> int:
    status = EXIT_FIXED if written else EXIT_CLEAN
    if declined or report.problems:
        status |= EXIT_LEFT
    return status


def _ask(ask: Callable[[str], str], change: Change, console: Console) -> str:
    """y = write, n = skip, e = edit the proposed note first, q = stop."""
    while True:
        answer = (ask("  write this? [y]es / [n]o / [e]dit / [q]uit: ") or "").strip().lower()[:1]
        if answer in ("y", "n", "q"):
            return answer
        if answer == "e" and change.rel:
            change.new = edit_text(change.new, Path(change.rel).name)
            console.print(diff_text(change), end="")


def edit_text(text: str, name: str) -> str:
    """*text* after the user has edited it in ``$VISUAL`` / ``$EDITOR``."""
    editor = os.environ.get("VISUAL") or os.environ.get("EDITOR") or "vi"
    fd, tmp = tempfile.mkstemp(suffix=f"-{name}")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fp:
            fp.write(text)
        subprocess.run([*editor.split(), tmp], check=False)
        return Path(tmp).read_text(encoding="utf-8")
    finally:
        os.unlink(tmp)
